### ISSUE TITLE
After clicking the "Authorize" button, the server error, can be not redirected to the redirect_uri

### ISSUE THREAD

**Issue by Lena0901** [Mashape/kong-oauth2-hello-world#3]
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/home/azureuser/kong-oauth2-hello-world/app.js:87:19)
    at Request.self.callback (/home/azureuser/kong-oauth2-hello-world/node_modules/request/request.js:197:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/azureuser/kong-oauth2-hello-world/node_modules/request/request.js:1050:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/azureuser/kong-oauth2-hello-world/node_modules/request/request.js:996:12)
    at emitNone (events.js:72:20)

**Comment by sudosourcerer** [comment]
+1 Also getting undefined error when trying to follow redirect_uri

**Comment by Tieske** [comment]
I just updated the readme, there were some thing outdated after previous updates. Can you try the readme instructions again @sudosourcerer ?

**Comment by Tieske** [comment]
ping @sudosourcerer

**Comment by venkateshmadala** [comment]
I am also getting Cannot GET /undefined after clicking on autherize button.

**Comment by Tieske** [comment]
@venkateshmadala can you be a bit more specific? exact error messages, where, and after what actions?

**Comment by zhuyunpeng** [comment]
i followed your actions but the browser shows "scope is invalid",why??

**Comment by zhuyunpeng** [comment]
finally  successed ! after i remove the scope parameter,but i still don't understand why,haha

**Comment by Initiallulu** [comment]
hey,there!  I want to know where to put authorization.jade, because of that, it shows Error: Failed to lookup view "authorization" in views directory "/etc/docker/views" at Function.app.render (/etc/docker/node_modules/_express@4.2.0@express/lib/application.js:492:17) at ServerResponse.res.render (/etc/docker/node_modules/_express@4.2.0@express/lib/response.js:802:7) at /etc/docker/app.js:110:11 at Request._callback (/etc/docker/app.js:75:5) at Request.self.callback (/etc/docker/node_modules/_request@2.58.0@request/request.js:197:22) at emitTwo (events.js:126:13) at Request.emit (events.js:214:7) at Request.<anonymous> (/etc/docker/node_modules/_request@2.58.0@request/request.js:1050:14) at emitOne (events.js:121:20) at Request.emit (events.js:211:7)

**Comment by Initiallulu** [comment]
I want to know why the authorization page says that Note: At this point the user has already been logged-in.how to log-out?Thanks!
